# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

import nodetool.metadata.types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

from nodetool.dsl.handles import OutputHandle, connect_field
import nodetool.nodes.lib.gzip
from nodetool.workflows.base_node import BaseNode


class GzipCompress(SingleOutputGraphNode[bytes], GraphNode[bytes]):
    """

    Compress bytes using gzip.
    gzip, compress, bytes

    Use cases:
    - Reduce size of binary data
    - Store assets in compressed form
    - Prepare data for network transfer
    """

    data: bytes | OutputHandle[bytes] = connect_field(
        default=b"", description="Data to compress"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.lib.gzip.GzipCompress

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


from nodetool.dsl.handles import OutputHandle, connect_field
from nodetool.workflows.base_node import BaseNode


class GzipDecompress(SingleOutputGraphNode[bytes], GraphNode[bytes]):
    """

    Decompress gzip data.
    gzip, decompress, bytes

    Use cases:
    - Restore compressed files
    - Read data from gzip archives
    - Process network payloads
    """

    data: bytes | OutputHandle[bytes] = connect_field(
        default=b"", description="Gzip data to decompress"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.lib.gzip.GzipDecompress

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
