# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.lib.pillow.draw


class Background(GraphNode[types.ImageRef]):
    """
    The Background Node creates a blank background.
    image, background, blank, base, layer
    This node is mainly used for generating a base layer for image processing tasks. It produces a uniform image, having a user-specified width, height and color. The color is given in a hexadecimal format, defaulting to white if not specified.

    #### Applications
    - As a base layer for creating composite images.
    - As a starting point for generating patterns or graphics.
    - When blank backgrounds of specific colors are required for visualization tasks.
    """

    width: int | OutputHandle[int] = connect_field(default=512, description=None)
    height: int | OutputHandle[int] = connect_field(default=512, description=None)
    color: types.ColorRef | OutputHandle[types.ColorRef] = connect_field(
        default=types.ColorRef(type="color", value="#FFFFFF"), description=None
    )

    @property
    def output(self) -> OutputHandle[types.ImageRef]:
        return typing.cast(OutputHandle[types.ImageRef], self._single_output_handle())

    @classmethod
    def get_node_type(cls):
        return "lib.pillow.draw.Background"


Background.model_rebuild(force=True)


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.lib.pillow.draw


class GaussianNoise(GraphNode[types.ImageRef]):
    """
    This node creates and adds Gaussian noise to an image.
    image, noise, gaussian, distortion, artifact

    The Gaussian Noise Node is designed to simulate realistic distortions that can occur in a photographic image. It generates a noise-filled image using the Gaussian (normal) distribution. The noise level can be adjusted using the mean and standard deviation parameters.

    #### Applications
    - Simulating sensor noise in synthetic data.
    - Testing image-processing algorithms' resilience to noise.
    - Creating artistic effects in images.
    """

    mean: float | OutputHandle[float] = connect_field(default=0.0, description=None)
    stddev: float | OutputHandle[float] = connect_field(default=1.0, description=None)
    width: int | OutputHandle[int] = connect_field(default=512, description=None)
    height: int | OutputHandle[int] = connect_field(default=512, description=None)

    @property
    def output(self) -> OutputHandle[types.ImageRef]:
        return typing.cast(OutputHandle[types.ImageRef], self._single_output_handle())

    @classmethod
    def get_node_type(cls):
        return "lib.pillow.draw.GaussianNoise"


GaussianNoise.model_rebuild(force=True)


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.lib.pillow.draw
import nodetool.nodes.lib.pillow.draw


class RenderText(GraphNode[types.ImageRef]):
    """
    This node allows you to add text to images.
    text, font, label, title, watermark, caption, image, overlay
    This node takes text, font updates, coordinates (where to place the text), and an image to work with. A user can use the Render Text Node to add a label or title to an image, watermark an image, or place a caption directly on an image.

    The Render Text Node offers customizable options, including the ability to choose the text's font, size, color, and alignment (left, center, or right). Text placement can also be defined, providing flexibility to place the text wherever you see fit.

    #### Applications
    - Labeling images in a image gallery or database.
    - Watermarking images for copyright protection.
    - Adding custom captions to photographs.
    - Creating instructional images to guide the reader's view.
    """

    TextAlignment: typing.ClassVar[type] = (
        nodetool.nodes.lib.pillow.draw.RenderText.TextAlignment
    )
    text: str | OutputHandle[str] = connect_field(
        default="", description="The text to render."
    )
    font: types.FontRef | OutputHandle[types.FontRef] = connect_field(
        default=types.FontRef(type="font", name="DejaVuSans"),
        description="The font to use.",
    )
    x: int | OutputHandle[int] = connect_field(
        default=0, description="The x coordinate."
    )
    y: int | OutputHandle[int] = connect_field(
        default=0, description="The y coordinate."
    )
    size: int | OutputHandle[int] = connect_field(
        default=12, description="The font size."
    )
    color: types.ColorRef | OutputHandle[types.ColorRef] = connect_field(
        default=types.ColorRef(type="color", value="#000000"),
        description="The font color.",
    )
    align: nodetool.nodes.lib.pillow.draw.RenderText.TextAlignment = Field(
        default=nodetool.nodes.lib.pillow.draw.RenderText.TextAlignment.LEFT,
        description=None,
    )
    image: types.ImageRef | OutputHandle[types.ImageRef] = connect_field(
        default=types.ImageRef(type="image", uri="", asset_id=None, data=None),
        description="The image to render on.",
    )

    @property
    def output(self) -> OutputHandle[types.ImageRef]:
        return typing.cast(OutputHandle[types.ImageRef], self._single_output_handle())

    @classmethod
    def get_node_type(cls):
        return "lib.pillow.draw.RenderText"


RenderText.model_rebuild(force=True)
