# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search.google
from nodetool.workflows.base_node import BaseNode

class GoogleFinance(SingleOutputGraphNode[dict[str, Any]], GraphNode[dict[str, Any]]):
    """

        Retrieve financial market data and stock information from Google Finance.
        google, finance, stocks, market, serp, trading
    """

    query: str | OutputHandle[str] = connect_field(default='', description='Stock symbol or company name to search for')
    window: str | OutputHandle[str] = connect_field(default='', description="Time window for financial data (e.g., '1d', '5d', '1m', '3m', '6m', '1y', '5y')")

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search.google.GoogleFinance

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search.google
from nodetool.workflows.base_node import BaseNode

class GoogleImages(SingleOutputGraphNode[list[types.ImageRef]], GraphNode[list[types.ImageRef]]):
    """

        Search Google Images to find visual content or perform reverse image search.
        google, images, serp, visual, reverse, search
    """

    keyword: str | OutputHandle[str] = connect_field(default='', description='Search query or keyword for images')
    image_url: str | OutputHandle[str] = connect_field(default='', description='URL of image for reverse image search')
    num_results: int | OutputHandle[int] = connect_field(default=20, description='Maximum number of image results to return')

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search.google.GoogleImages

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search.google
from nodetool.workflows.base_node import BaseNode

class GoogleJobs(GraphNode[nodetool.nodes.search.google.GoogleJobs.OutputType]):
    """

        Search Google Jobs for employment opportunities and job listings.
        google, jobs, employment, careers, serp, hiring
    """

    query: str | OutputHandle[str] = connect_field(default='', description='Job title, skills, or company name to search for')
    location: str | OutputHandle[str] = connect_field(default='', description='Geographic location for job search')
    num_results: int | OutputHandle[int] = connect_field(default=10, description='Maximum number of job results to return')

    @property
    def out(self) -> "GoogleJobsOutputs":
        return GoogleJobsOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search.google.GoogleJobs

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()

class GoogleJobsOutputs(OutputsProxy):
    @property
    def results(self) -> OutputHandle[list[dict]]:
        return typing.cast(OutputHandle[list[dict]], self['results'])

    @property
    def text(self) -> OutputHandle[str]:
        return typing.cast(OutputHandle[str], self['text'])


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search.google
from nodetool.workflows.base_node import BaseNode

class GoogleLens(GraphNode[nodetool.nodes.search.google.GoogleLens.OutputType]):
    """

        Analyze images using Google Lens to find visual matches and related content.
        google, lens, visual, image, search, serp, identify
    """

    image_url: str | OutputHandle[str] = connect_field(default='', description='URL of the image to analyze with Google Lens')
    num_results: int | OutputHandle[int] = connect_field(default=10, description='Maximum number of visual search results to return')

    @property
    def out(self) -> "GoogleLensOutputs":
        return GoogleLensOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search.google.GoogleLens

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()

class GoogleLensOutputs(OutputsProxy):
    @property
    def results(self) -> OutputHandle[list[dict]]:
        return typing.cast(OutputHandle[list[dict]], self['results'])

    @property
    def images(self) -> OutputHandle[list[types.ImageRef]]:
        return typing.cast(OutputHandle[list[types.ImageRef]], self['images'])


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search.google
from nodetool.workflows.base_node import BaseNode

class GoogleMaps(GraphNode[nodetool.nodes.search.google.GoogleMaps.OutputType]):
    """

        Search Google Maps for places, businesses, and get location details.
        google, maps, places, locations, serp, geography
    """

    query: str | OutputHandle[str] = connect_field(default='', description='Place name, address, or location query')
    num_results: int | OutputHandle[int] = connect_field(default=10, description='Maximum number of map results to return')

    @property
    def out(self) -> "GoogleMapsOutputs":
        return GoogleMapsOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search.google.GoogleMaps

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()

class GoogleMapsOutputs(OutputsProxy):
    @property
    def results(self) -> OutputHandle[list[dict]]:
        return typing.cast(OutputHandle[list[dict]], self['results'])

    @property
    def text(self) -> OutputHandle[str]:
        return typing.cast(OutputHandle[str], self['text'])


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search.google
from nodetool.workflows.base_node import BaseNode

class GoogleNews(GraphNode[nodetool.nodes.search.google.GoogleNews.OutputType]):
    """

        Search Google News to retrieve current news articles and headlines.
        google, news, serp, articles, journalism
    """

    keyword: str | OutputHandle[str] = connect_field(default='', description='Search query or keyword for news articles')
    num_results: int | OutputHandle[int] = connect_field(default=10, description='Maximum number of news results to return')

    @property
    def out(self) -> "GoogleNewsOutputs":
        return GoogleNewsOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search.google.GoogleNews

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()

class GoogleNewsOutputs(OutputsProxy):
    @property
    def results(self) -> OutputHandle[list[dict]]:
        return typing.cast(OutputHandle[list[dict]], self['results'])

    @property
    def text(self) -> OutputHandle[str]:
        return typing.cast(OutputHandle[str], self['text'])


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search.google
from nodetool.workflows.base_node import BaseNode

class GoogleSearch(GraphNode[nodetool.nodes.search.google.GoogleSearch.OutputType]):
    """

        Search Google to retrieve organic search results from the web.
        google, search, serp, web, query
    """

    keyword: str | OutputHandle[str] = connect_field(default='', description='Search query or keyword to search for')
    num_results: int | OutputHandle[int] = connect_field(default=10, description='Maximum number of results to return')

    @property
    def out(self) -> "GoogleSearchOutputs":
        return GoogleSearchOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search.google.GoogleSearch

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()

class GoogleSearchOutputs(OutputsProxy):
    @property
    def results(self) -> OutputHandle[list[dict]]:
        return typing.cast(OutputHandle[list[dict]], self['results'])

    @property
    def text(self) -> OutputHandle[str]:
        return typing.cast(OutputHandle[str], self['text'])


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search.google
from nodetool.workflows.base_node import BaseNode

class GoogleShopping(GraphNode[nodetool.nodes.search.google.GoogleShopping.OutputType]):
    """

        Search Google Shopping for products with filters and pricing information.
        google, shopping, products, ecommerce, serp, prices
    """

    query: str | OutputHandle[str] = connect_field(default='', description='Product name or description to search for')
    country: str | OutputHandle[str] = connect_field(default='us', description="Country code for shopping search (e.g., 'us', 'uk', 'ca')")
    min_price: int | OutputHandle[int] = connect_field(default=0, description='Minimum price filter for products')
    max_price: int | OutputHandle[int] = connect_field(default=0, description='Maximum price filter for products')
    condition: str | OutputHandle[str] = connect_field(default='', description="Product condition filter (e.g., 'new', 'used', 'refurbished')")
    sort_by: str | OutputHandle[str] = connect_field(default='', description="Sort order for results (e.g., 'price_low_to_high', 'price_high_to_low', 'review_score')")
    num_results: int | OutputHandle[int] = connect_field(default=10, description='Maximum number of shopping results to return')

    @property
    def out(self) -> "GoogleShoppingOutputs":
        return GoogleShoppingOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search.google.GoogleShopping

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()

class GoogleShoppingOutputs(OutputsProxy):
    @property
    def results(self) -> OutputHandle[list[dict]]:
        return typing.cast(OutputHandle[list[dict]], self['results'])

    @property
    def text(self) -> OutputHandle[str]:
        return typing.cast(OutputHandle[str], self['text'])


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search._base
from nodetool.workflows.base_node import BaseNode

class SerpNode(SingleOutputGraphNode[typing.Any], GraphNode[typing.Any]):
    """
    Base class for SerpAPI-powered search nodes.

        Provides common provider initialization and the search_raw helper.
        Subclasses implement process() and call self._search_raw() instead of
        repeating the 8-line provider boilerplate.
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search._base.SerpNode

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


