# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search.more_engines
from nodetool.workflows.base_node import BaseNode

class BingShopping(GraphNode[nodetool.nodes.search.more_engines.BingShopping.OutputType]):
    """

        Search Bing Shopping for product listings with prices and seller info.
        bing, shopping, products, prices, ecommerce, deals, buy
    """

    query: str | OutputHandle[str] = connect_field(default='', description='Product search query')
    num_results: int | OutputHandle[int] = connect_field(default=10, description='Maximum number of shopping results to return')

    @property
    def out(self) -> "BingShoppingOutputs":
        return BingShoppingOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search.more_engines.BingShopping

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()

class BingShoppingOutputs(OutputsProxy):
    @property
    def results(self) -> OutputHandle[list[dict]]:
        return typing.cast(OutputHandle[list[dict]], self['results'])

    @property
    def text(self) -> OutputHandle[str]:
        return typing.cast(OutputHandle[str], self['text'])


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search.more_engines
from nodetool.workflows.base_node import BaseNode

class BingVideos(GraphNode[nodetool.nodes.search.more_engines.BingVideos.OutputType]):
    """

        Search Bing Videos for video content across the web.
        bing, videos, search, media, streaming, content
    """

    query: str | OutputHandle[str] = connect_field(default='', description='Video search query')
    num_results: int | OutputHandle[int] = connect_field(default=10, description='Maximum number of video results to return')

    @property
    def out(self) -> "BingVideosOutputs":
        return BingVideosOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search.more_engines.BingVideos

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()

class BingVideosOutputs(OutputsProxy):
    @property
    def results(self) -> OutputHandle[list[dict]]:
        return typing.cast(OutputHandle[list[dict]], self['results'])

    @property
    def text(self) -> OutputHandle[str]:
        return typing.cast(OutputHandle[str], self['text'])


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search.more_engines
from nodetool.workflows.base_node import BaseNode

class GoogleMapsReviews(GraphNode[nodetool.nodes.search.more_engines.GoogleMapsReviews.OutputType]):
    """

        Retrieve reviews for a Google Maps place by its data_id.
        Use Google Maps search to find a place's data_id first.
        google, maps, reviews, places, ratings, local, business, restaurant
    """

    ReviewSortOrder: typing.ClassVar[type] = nodetool.nodes.search.more_engines.ReviewSortOrder

    data_id: str | OutputHandle[str] = connect_field(default='', description='Google Maps place data_id (obtain from a Google Maps search result)')
    sort_by: nodetool.nodes.search.more_engines.ReviewSortOrder = Field(default=nodetool.nodes.search.more_engines.ReviewSortOrder.MOST_RELEVANT, description='Sort order for reviews')
    num_results: int | OutputHandle[int] = connect_field(default=10, description='Number of reviews to return (1-20)')

    @property
    def out(self) -> "GoogleMapsReviewsOutputs":
        return GoogleMapsReviewsOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search.more_engines.GoogleMapsReviews

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()

class GoogleMapsReviewsOutputs(OutputsProxy):
    @property
    def results(self) -> OutputHandle[list[dict]]:
        return typing.cast(OutputHandle[list[dict]], self['results'])

    @property
    def text(self) -> OutputHandle[str]:
        return typing.cast(OutputHandle[str], self['text'])


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search._base
from nodetool.workflows.base_node import BaseNode

class SerpNode(SingleOutputGraphNode[typing.Any], GraphNode[typing.Any]):
    """
    Base class for SerpAPI-powered search nodes.

        Provides common provider initialization and the search_raw helper.
        Subclasses implement process() and call self._search_raw() instead of
        repeating the 8-line provider boilerplate.
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search._base.SerpNode

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search.more_engines
from nodetool.workflows.base_node import BaseNode

class YouTubeTranscript(GraphNode[nodetool.nodes.search.more_engines.YouTubeTranscript.OutputType]):
    """

        Retrieve the full transcript of a YouTube video by its video ID.
        Concatenates all transcript segments into a single text output.
        youtube, transcript, subtitles, captions, text, video, speech
    """

    video_id: str | OutputHandle[str] = connect_field(default='', description='YouTube video ID (the part after v= in the URL)')
    lang: str | OutputHandle[str] = connect_field(default='en', description="Language code for the transcript (e.g., 'en', 'es', 'de')")

    @property
    def out(self) -> "YouTubeTranscriptOutputs":
        return YouTubeTranscriptOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search.more_engines.YouTubeTranscript

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()

class YouTubeTranscriptOutputs(OutputsProxy):
    @property
    def text(self) -> OutputHandle[str]:
        return typing.cast(OutputHandle[str], self['text'])

    @property
    def segments(self) -> OutputHandle[list[dict]]:
        return typing.cast(OutputHandle[list[dict]], self['segments'])


