# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search.retail
from nodetool.workflows.base_node import BaseNode

class AppleAppStore(GraphNode[nodetool.nodes.search.retail.AppleAppStore.OutputType]):
    """

        Search the Apple App Store for apps, games, and utilities.
        apple, app store, search, apps, ios, iphone, ipad, mobile
    """

    query: str | OutputHandle[str] = connect_field(default='', description='App name or keyword to search for')
    num_results: int | OutputHandle[int] = connect_field(default=10, description='Maximum number of results to return')
    country: str | OutputHandle[str] = connect_field(default='us', description="Two-letter country code (e.g., 'us', 'gb', 'de')")

    @property
    def out(self) -> "AppleAppStoreOutputs":
        return AppleAppStoreOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search.retail.AppleAppStore

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()

class AppleAppStoreOutputs(OutputsProxy):
    @property
    def results(self) -> OutputHandle[list[dict]]:
        return typing.cast(OutputHandle[list[dict]], self['results'])

    @property
    def text(self) -> OutputHandle[str]:
        return typing.cast(OutputHandle[str], self['text'])


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search.retail
from nodetool.workflows.base_node import BaseNode

class HomeDepotProduct(SingleOutputGraphNode[dict], GraphNode[dict]):
    """

        Get detailed information about a specific Home Depot product by product ID.
        home depot, product, details, home improvement, hardware
    """

    product_id: str | OutputHandle[str] = connect_field(default='', description='Home Depot product ID to look up')

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search.retail.HomeDepotProduct

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search.retail
from nodetool.workflows.base_node import BaseNode

class HomeDepotSearch(GraphNode[nodetool.nodes.search.retail.HomeDepotSearch.OutputType]):
    """

        Search Home Depot for products, tools, and home improvement items.
        home depot, search, products, hardware, tools, home improvement
    """

    query: str | OutputHandle[str] = connect_field(default='', description='Product name or description to search for')
    num_results: int | OutputHandle[int] = connect_field(default=10, description='Maximum number of results to return')

    @property
    def out(self) -> "HomeDepotSearchOutputs":
        return HomeDepotSearchOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search.retail.HomeDepotSearch

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()

class HomeDepotSearchOutputs(OutputsProxy):
    @property
    def results(self) -> OutputHandle[list[dict]]:
        return typing.cast(OutputHandle[list[dict]], self['results'])

    @property
    def text(self) -> OutputHandle[str]:
        return typing.cast(OutputHandle[str], self['text'])


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.search._base
from nodetool.workflows.base_node import BaseNode

class SerpNode(SingleOutputGraphNode[typing.Any], GraphNode[typing.Any]):
    """
    Base class for SerpAPI-powered search nodes.

        Provides common provider initialization and the search_raw helper.
        Subclasses implement process() and call self._search_raw() instead of
        repeating the 8-line provider boilerplate.
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.search._base.SerpNode

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


